### PR TITLE
Release 2.1.1

### PR DESCRIPTION
**Pull request by lartist**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Merge dev into master
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? |
| How to test?  |

### CODE REVIEW

**Review by jolelievre — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @lartist 

I have checked your PR. I found these issues :

**Issue 1 :** The logo and the description in the 8.0.2 is not coherent with 1.7.8.8 with the new module 

**PS1788 :** 

image


**PS8.0.2 :** The logo is different and there is no the read more.

image


**8.0.2 fresh install** : With the v2.0.3, the logo was OK

image

**Issue 2 :**  The trends is not displayed on the 1788

**PS1788: NOK** 

image

**PS8.0.2 : OK**

image

Could you please check it ?

Thank You!

**Comment by lartist** [comment]
Hi @HanaRebaiQA , I can't reproduce the following bug:
>Issue 2 : The trends is not displayed on the 1788

When I upload the 2.1.1 zip the trends is still present. Can you try one more time plz. Maybe something wrong occurred when you upgraded the module

**Comment by lartist** [comment]
@HanaRebaiQA 

1. The logo is different but it's on purpose
2. The read more was removed here:
[https://github.com/PrestaShop/PrestaShop/commit/04d49a831aab327dbfa03015c5c50957372ff23d#diff-030ad9930d663ee93b4c7fa[…]a67484fd87ca01c1314b7L90-L94](https://github.com/PrestaShop/PrestaShop/commit/04d49a831aab327dbfa03015c5c50957372ff23d#diff-030ad9930d663ee93b4c7fad5494842b74affa38140a67484fd87ca01c1314b7L90-L94)
3. I still have trends when I upgrade to 2.1.1 on PS 1.7.8.8.

Can you plz check again the point 3 because if finally it was a compilation error or something like this, this PR is definitely ok.

**Comment by nicosomb** [comment]
Thank you @lartist !
